spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/auth
    username: admin
    password: admin

  flyway:
    url: jdbc:postgresql://localhost:5435/auth
    user: admin
    password: admin
    enabled: true
    locations:
      - 'classpath:db/migration'

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: true

logging:
  level:
    com:example: debug